apiVersion: v1
kind: Secret
metadata:
  name: webhookrelay-api
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value }}
  {{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhookrelay-publisher
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.publisher.secrets }}
  {{ $key }}: {{ $value }}
  {{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhookrelay-provisioner
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.provisioner.secrets }}
  {{ $key }}: {{ $value }}
  {{- end}}