// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: pkg/api/v1/webhookrelay.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebhookStatus represents the current status of a webhook
type WebhookStatus int32

const (
	WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED WebhookStatus = 0
	WebhookStatus_WEBHOOK_STATUS_UNKNOWN     WebhookStatus = 1
	WebhookStatus_WEBHOOK_STATUS_PENDING     WebhookStatus = 2
	WebhookStatus_WEBHOOK_STATUS_FAILED      WebhookStatus = 3
	WebhookStatus_WEBHOOK_STATUS_SUCCEEDED   WebhookStatus = 4
)

// Enum value maps for WebhookStatus.
var (
	WebhookStatus_name = map[int32]string{
		0: "WEBHOOK_STATUS_UNSPECIFIED",
		1: "WEBHOOK_STATUS_UNKNOWN",
		2: "WEBHOOK_STATUS_PENDING",
		3: "WEBHOOK_STATUS_FAILED",
		4: "WEBHOOK_STATUS_SUCCEEDED",
	}
	WebhookStatus_value = map[string]int32{
		"WEBHOOK_STATUS_UNSPECIFIED": 0,
		"WEBHOOK_STATUS_UNKNOWN":     1,
		"WEBHOOK_STATUS_PENDING":     2,
		"WEBHOOK_STATUS_FAILED":      3,
		"WEBHOOK_STATUS_SUCCEEDED":   4,
	}
)

func (x WebhookStatus) Enum() *WebhookStatus {
	p := new(WebhookStatus)
	*p = x
	return p
}

func (x WebhookStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_webhookrelay_proto_enumTypes[0].Descriptor()
}

func (WebhookStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_webhookrelay_proto_enumTypes[0]
}

func (x WebhookStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookStatus.Descriptor instead.
func (WebhookStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{0}
}

// Webhook represents a webhook resource
type Webhook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the webhook
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Target URL to send the webhook payload to
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Base64 encoded bytes payload
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Timestamp when the webhook was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the webhook was deleted (null if not deleted)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// Timestamp when the webhook was published (null if not published)
	PublishedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	// Timestamp when the webhook was provisioned (null if not provisioned)
	ProvisionedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=provisioned_at,json=provisionedAt,proto3,oneof" json:"provisioned_at,omitempty"`
	// List of delivery attempts
	Attempts []*WebhookAttempt `protobuf:"bytes,8,rep,name=attempts,proto3" json:"attempts,omitempty"`
	// Current status of the webhook
	Status        WebhookStatus `protobuf:"varint,9,opt,name=status,proto3,enum=webhookrelay.api.v1.WebhookStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Webhook) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Webhook) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Webhook) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Webhook) GetProvisionedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProvisionedAt
	}
	return nil
}

func (x *Webhook) GetAttempts() []*WebhookAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *Webhook) GetStatus() WebhookStatus {
	if x != nil {
		return x.Status
	}
	return WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED
}

// WebhookAttempt represents a delivery attempt for a webhook
type WebhookAttempt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the attempt was made
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// HTTP response status code from the target
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// Additional attempt information
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookAttempt) Reset() {
	*x = WebhookAttempt{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookAttempt) ProtoMessage() {}

func (x *WebhookAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookAttempt.ProtoReflect.Descriptor instead.
func (*WebhookAttempt) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookAttempt) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WebhookAttempt) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WebhookAttempt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetWebhookRequest is the request for getting a single webhook
type GetWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the webhook to retrieve
	WebhookId     string `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookRequest) Reset() {
	*x = GetWebhookRequest{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookRequest) ProtoMessage() {}

func (x *GetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{2}
}

func (x *GetWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

// GetWebhookResponse is the response for getting a single webhook
type GetWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested webhook
	Webhook       *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookResponse) Reset() {
	*x = GetWebhookResponse{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookResponse) ProtoMessage() {}

func (x *GetWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{3}
}

func (x *GetWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

// ListWebhooksRequest is the request for listing webhooks
type ListWebhooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset for pagination
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Limit for pagination
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Whether to include deleted webhooks
	Deleted       bool `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{4}
}

func (x *ListWebhooksRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListWebhooksRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWebhooksRequest) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// ListWebhooksResponse is the response for listing webhooks
type ListWebhooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of webhooks
	Webhooks      []*Webhook `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{5}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

// CreateWebhookRequest is the request for creating a webhook
type CreateWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target URL to send the webhook payload to
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Base64 encoded bytes payload
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Idempotency token for the request
	IdempotencyToken string `protobuf:"bytes,3,opt,name=idempotency_token,json=idempotencyToken,proto3" json:"idempotency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWebhookRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateWebhookRequest) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

// CreateWebhookResponse is the response for creating a webhook
type CreateWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created webhook
	Webhook       *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookResponse) Reset() {
	*x = CreateWebhookResponse{}
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookResponse) ProtoMessage() {}

func (x *CreateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_webhookrelay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookResponse.ProtoReflect.Descriptor instead.
func (*CreateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_webhookrelay_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

var File_pkg_api_v1_webhookrelay_proto protoreflect.FileDescriptor

const file_pkg_api_v1_webhookrelay_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/api/v1/webhookrelay.proto\x12\x13webhookrelay.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x04\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12B\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vpublishedAt\x88\x01\x01\x12F\n" +
	"\x0eprovisioned_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\rprovisionedAt\x88\x01\x01\x12?\n" +
	"\battempts\x18\b \x03(\v2#.webhookrelay.api.v1.WebhookAttemptR\battempts\x12:\n" +
	"\x06status\x18\t \x01(\x0e2\".webhookrelay.api.v1.WebhookStatusR\x06statusB\r\n" +
	"\v_deleted_atB\x0f\n" +
	"\r_published_atB\x11\n" +
	"\x0f_provisioned_at\"|\n" +
	"\x0eWebhookAttempt\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x11GetWebhookRequest\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\"L\n" +
	"\x12GetWebhookResponse\x126\n" +
	"\awebhook\x18\x01 \x01(\v2\x1c.webhookrelay.api.v1.WebhookR\awebhook\"]\n" +
	"\x13ListWebhooksRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\"P\n" +
	"\x14ListWebhooksResponse\x128\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x1c.webhookrelay.api.v1.WebhookR\bwebhooks\"u\n" +
	"\x14CreateWebhookRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12+\n" +
	"\x11idempotency_token\x18\x03 \x01(\tR\x10idempotencyToken\"O\n" +
	"\x15CreateWebhookResponse\x126\n" +
	"\awebhook\x18\x01 \x01(\v2\x1c.webhookrelay.api.v1.WebhookR\awebhook*\xa0\x01\n" +
	"\rWebhookStatus\x12\x1e\n" +
	"\x1aWEBHOOK_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WEBHOOK_STATUS_UNKNOWN\x10\x01\x12\x1a\n" +
	"\x16WEBHOOK_STATUS_PENDING\x10\x02\x12\x19\n" +
	"\x15WEBHOOK_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18WEBHOOK_STATUS_SUCCEEDED\x10\x042\xc1\x02\n" +
	"\x13WebhookRelayService\x12]\n" +
	"\n" +
	"GetWebhook\x12&.webhookrelay.api.v1.GetWebhookRequest\x1a'.webhookrelay.api.v1.GetWebhookResponse\x12c\n" +
	"\fListWebhooks\x12(.webhookrelay.api.v1.ListWebhooksRequest\x1a).webhookrelay.api.v1.ListWebhooksResponse\x12f\n" +
	"\rCreateWebhook\x12).webhookrelay.api.v1.CreateWebhookRequest\x1a*.webhookrelay.api.v1.CreateWebhookResponseB2Z0github.com/broswen/webhookrelay/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_webhookrelay_proto_rawDescOnce sync.Once
	file_pkg_api_v1_webhookrelay_proto_rawDescData []byte
)

func file_pkg_api_v1_webhookrelay_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_webhookrelay_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_webhookrelay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_webhookrelay_proto_rawDesc), len(file_pkg_api_v1_webhookrelay_proto_rawDesc)))
	})
	return file_pkg_api_v1_webhookrelay_proto_rawDescData
}

var file_pkg_api_v1_webhookrelay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_v1_webhookrelay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_api_v1_webhookrelay_proto_goTypes = []any{
	(WebhookStatus)(0),            // 0: webhookrelay.api.v1.WebhookStatus
	(*Webhook)(nil),               // 1: webhookrelay.api.v1.Webhook
	(*WebhookAttempt)(nil),        // 2: webhookrelay.api.v1.WebhookAttempt
	(*GetWebhookRequest)(nil),     // 3: webhookrelay.api.v1.GetWebhookRequest
	(*GetWebhookResponse)(nil),    // 4: webhookrelay.api.v1.GetWebhookResponse
	(*ListWebhooksRequest)(nil),   // 5: webhookrelay.api.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),  // 6: webhookrelay.api.v1.ListWebhooksResponse
	(*CreateWebhookRequest)(nil),  // 7: webhookrelay.api.v1.CreateWebhookRequest
	(*CreateWebhookResponse)(nil), // 8: webhookrelay.api.v1.CreateWebhookResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pkg_api_v1_webhookrelay_proto_depIdxs = []int32{
	9,  // 0: webhookrelay.api.v1.Webhook.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: webhookrelay.api.v1.Webhook.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 2: webhookrelay.api.v1.Webhook.published_at:type_name -> google.protobuf.Timestamp
	9,  // 3: webhookrelay.api.v1.Webhook.provisioned_at:type_name -> google.protobuf.Timestamp
	2,  // 4: webhookrelay.api.v1.Webhook.attempts:type_name -> webhookrelay.api.v1.WebhookAttempt
	0,  // 5: webhookrelay.api.v1.Webhook.status:type_name -> webhookrelay.api.v1.WebhookStatus
	9,  // 6: webhookrelay.api.v1.WebhookAttempt.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 7: webhookrelay.api.v1.GetWebhookResponse.webhook:type_name -> webhookrelay.api.v1.Webhook
	1,  // 8: webhookrelay.api.v1.ListWebhooksResponse.webhooks:type_name -> webhookrelay.api.v1.Webhook
	1,  // 9: webhookrelay.api.v1.CreateWebhookResponse.webhook:type_name -> webhookrelay.api.v1.Webhook
	3,  // 10: webhookrelay.api.v1.WebhookRelayService.GetWebhook:input_type -> webhookrelay.api.v1.GetWebhookRequest
	5,  // 11: webhookrelay.api.v1.WebhookRelayService.ListWebhooks:input_type -> webhookrelay.api.v1.ListWebhooksRequest
	7,  // 12: webhookrelay.api.v1.WebhookRelayService.CreateWebhook:input_type -> webhookrelay.api.v1.CreateWebhookRequest
	4,  // 13: webhookrelay.api.v1.WebhookRelayService.GetWebhook:output_type -> webhookrelay.api.v1.GetWebhookResponse
	6,  // 14: webhookrelay.api.v1.WebhookRelayService.ListWebhooks:output_type -> webhookrelay.api.v1.ListWebhooksResponse
	8,  // 15: webhookrelay.api.v1.WebhookRelayService.CreateWebhook:output_type -> webhookrelay.api.v1.CreateWebhookResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_webhookrelay_proto_init() }
func file_pkg_api_v1_webhookrelay_proto_init() {
	if File_pkg_api_v1_webhookrelay_proto != nil {
		return
	}
	file_pkg_api_v1_webhookrelay_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_webhookrelay_proto_rawDesc), len(file_pkg_api_v1_webhookrelay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_webhookrelay_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_webhookrelay_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_webhookrelay_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_webhookrelay_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_webhookrelay_proto = out.File
	file_pkg_api_v1_webhookrelay_proto_goTypes = nil
	file_pkg_api_v1_webhookrelay_proto_depIdxs = nil
}
