// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: pkg/api/v1/webhookrelay.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookRelayService_GetWebhook_FullMethodName    = "/webhookrelay.api.v1.WebhookRelayService/GetWebhook"
	WebhookRelayService_ListWebhooks_FullMethodName  = "/webhookrelay.api.v1.WebhookRelayService/ListWebhooks"
	WebhookRelayService_CreateWebhook_FullMethodName = "/webhookrelay.api.v1.WebhookRelayService/CreateWebhook"
)

// WebhookRelayServiceClient is the client API for WebhookRelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebhookRelayService provides webhook management functionality
type WebhookRelayServiceClient interface {
	// Get retrieves a single webhook by ID
	GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*GetWebhookResponse, error)
	// List retrieves multiple webhooks with pagination
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error)
	// Create creates a new webhook
	CreateWebhook(ctx context.Context, in *CreateWebhookRequest, opts ...grpc.CallOption) (*CreateWebhookResponse, error)
}

type webhookRelayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookRelayServiceClient(cc grpc.ClientConnInterface) WebhookRelayServiceClient {
	return &webhookRelayServiceClient{cc}
}

func (c *webhookRelayServiceClient) GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*GetWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookRelayService_GetWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookRelayServiceClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhooksResponse)
	err := c.cc.Invoke(ctx, WebhookRelayService_ListWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookRelayServiceClient) CreateWebhook(ctx context.Context, in *CreateWebhookRequest, opts ...grpc.CallOption) (*CreateWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookRelayService_CreateWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookRelayServiceServer is the server API for WebhookRelayService service.
// All implementations must embed UnimplementedWebhookRelayServiceServer
// for forward compatibility.
//
// WebhookRelayService provides webhook management functionality
type WebhookRelayServiceServer interface {
	// Get retrieves a single webhook by ID
	GetWebhook(context.Context, *GetWebhookRequest) (*GetWebhookResponse, error)
	// List retrieves multiple webhooks with pagination
	ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error)
	// Create creates a new webhook
	CreateWebhook(context.Context, *CreateWebhookRequest) (*CreateWebhookResponse, error)
	mustEmbedUnimplementedWebhookRelayServiceServer()
}

// UnimplementedWebhookRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookRelayServiceServer struct{}

func (UnimplementedWebhookRelayServiceServer) GetWebhook(context.Context, *GetWebhookRequest) (*GetWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhook not implemented")
}
func (UnimplementedWebhookRelayServiceServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedWebhookRelayServiceServer) CreateWebhook(context.Context, *CreateWebhookRequest) (*CreateWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebhook not implemented")
}
func (UnimplementedWebhookRelayServiceServer) mustEmbedUnimplementedWebhookRelayServiceServer() {}
func (UnimplementedWebhookRelayServiceServer) testEmbeddedByValue()                             {}

// UnsafeWebhookRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookRelayServiceServer will
// result in compilation errors.
type UnsafeWebhookRelayServiceServer interface {
	mustEmbedUnimplementedWebhookRelayServiceServer()
}

func RegisterWebhookRelayServiceServer(s grpc.ServiceRegistrar, srv WebhookRelayServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookRelayService_ServiceDesc, srv)
}

func _WebhookRelayService_GetWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRelayServiceServer).GetWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRelayService_GetWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRelayServiceServer).GetWebhook(ctx, req.(*GetWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookRelayService_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRelayServiceServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRelayService_ListWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRelayServiceServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookRelayService_CreateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRelayServiceServer).CreateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRelayService_CreateWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRelayServiceServer).CreateWebhook(ctx, req.(*CreateWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookRelayService_ServiceDesc is the grpc.ServiceDesc for WebhookRelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookRelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webhookrelay.api.v1.WebhookRelayService",
	HandlerType: (*WebhookRelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWebhook",
			Handler:    _WebhookRelayService_GetWebhook_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _WebhookRelayService_ListWebhooks_Handler,
		},
		{
			MethodName: "CreateWebhook",
			Handler:    _WebhookRelayService_CreateWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/webhookrelay.proto",
}
