apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookrelay-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: webhookrelay
      app.kubernetes.io/instance: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhookrelay
        app.kubernetes.io/instance: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: webhookrelay-api
            - secretRef:
                name: webhookrelay-api
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.api.metrics.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}