apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookrelay-provisioner
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.provisioner.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: webhookrelay
      app.kubernetes.io/instance: provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhookrelay
        app.kubernetes.io/instance: provisioner
    spec:
      containers:
        - name: provisioner
          image: "{{ .Values.provisioner.image.repository }}:{{ .Values.provisioner.image.tag }}"
          imagePullPolicy: {{ .Values.provisioner.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: webhookrelay-provisioner
            - secretRef:
                name: webhookrelay-provisioner
          ports:
            - name: metrics
              containerPort: {{ .Values.provisioner.metrics.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.provisioner.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.provisioner.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.provisioner.resources | nindent 12 }}